#!/usr/bin/env python3 -u

import boto3
from pyropossum.aws.pollers import SqsPoller
from pyropossum.arduino.core import Arduino, ArduinoException
from pyropossum.arduino.commands import ENABLE, DISABLE
from pyropossum.config import load_config, configure_logging

logger = configure_logging(__name__)
config = load_config()

PROFILE_NAME = config["send-profile"]
REGION_NAME = config["region"]
STACK_NAME = config["stack"]

session = boto3.Session(profile_name=PROFILE_NAME, region_name=REGION_NAME)

queue_url = {resource["LogicalResourceId"] : resource['PhysicalResourceId'] for resource in session.client('cloudformation').describe_stack_resources(StackName=STACK_NAME)['StackResources']}['SQSQueue']

session.client('sqs').send_message(QueueUrl=queue_url, MessageBody='{"source":"CLI","enable":false, "targets":["LIGHT"]}')
